Operations on Matrix using Numpy

In [1]:
import numpy as np
climate_data=np.array([[73,67,63],
                       [91,88,64],
                       [87,134,58],
                       [102,43,37],
                       [69,96,70]])
weights=np.array([0.3,0.2,0.5])

In [2]:
weights

array([0.3, 0.2, 0.5])

In [3]:
climate_data

array([[ 73,  67,  63],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [5]:
np.matmul(climate_data,weights) #Matrix Multiplication of 2 matices named as climate_data & weights

array([66.8, 76.9, 81.9, 57.7, 74.9])

In [6]:
#Importing to access some file using it's URL address and saving it as "climate.txt"
import urllib.request  
urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x14822226160>)

In [7]:
#Converting the extracted CSV file to a numpy array by skipping its headers
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1) 

In [8]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [14]:
weights=([0.3,0.4,0.5])
weights

[0.3, 0.4, 0.5]

In [15]:
yeilds=climate_data@weights  # @ is used for Matrix Multiplication

In [16]:
yeilds

array([87.4, 72.7, 74.2, ..., 83.5, 94.9, 81.2])

In [17]:
#Reshaping the array without changing its data(like transposing)
yeilds.reshape(10000,1) 

array([[87.4],
       [72.7],
       [74.2],
       ...,
       [83.5],
       [94.9],
       [81.2]])

In [18]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [19]:
#Concatenating 2 array's
climate_results=np.concatenate((climate_data,yeilds.reshape(10000,1)),axis=1)
climate_results

array([[25. , 76. , 99. , 87.4],
       [39. , 65. , 70. , 72.7],
       [59. , 45. , 77. , 74.2],
       ...,
       [99. , 62. , 58. , 83.5],
       [70. , 71. , 91. , 94.9],
       [92. , 39. , 76. , 81.2]])

In [21]:
#Saving the final concatenated array back into the text file with its headers
np.savetxt('climate_results.txt',climate_results,
            fmt='%.2f',
            delimiter=',',
            header='temperature,rainfall,humidity,yeild_of_apples',
            comments='')

Numpy functions:
Mathematics: np.sum, np.exp, np.round, arithemtic operators

Array manipulation: np.reshape, np.stack, np.concatenate, np.split

Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals

Statistics: np.mean, np.median, np.std, np.max

All functions in Numpy -----> https://numpy.org/doc/stable/reference/routines.html