# Function to calculate mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

In [4]:
import numpy as np

def calculate(list):
      if len(list) != 9:
        raise ValueError("List must contain nine numbers.")

      m = np.array(list).reshape([3, 3])
      print(m)
      calculations = {
        "mean": [m.mean(0).tolist(), m.mean(1).tolist(), m.mean()],  #'mean': [axis0(horzitonally,i.e,[0,3,6]) , axis1(vertically) , flattened(whole list)]
        "variance": [m.var(0).tolist(), m.var(1).tolist(), m.var()],
        "standard deviation": [m.std(0).tolist(), m.std(1).tolist(), m.std()],
        "max": [m.max(0).tolist(), m.max(1).tolist(), m.max()],
        "min": [m.min(0).tolist(), m.min(1).tolist(), m.min()],
        "sum": [m.sum(0).tolist(), m.sum(1).tolist(), m.sum()]
        
      }

      return calculations

print(calculate([0,1,2,3,4,5,6,7,8]))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}
